name: Build, Push & Deploy to K8s

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build base image
        working-directory: itelemetry-openjdk-playwright
        run: docker build . -t "ghcr.io/itelemetry/itelemetry-openjdk-playwright:${{ github.run_id }}" -t ghcr.io/itelemetry/itelemetry-openjdk-playwright:latest
      - name: Push base image
        run: docker push -a ghcr.io/itelemetry/itelemetry-openjdk-playwright